### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by nicho1asdev** [akusio/KernBypass-Public#6]
So it doesn’t seem to work for me on iOS 13.3 iPhone XR. When I try to uninstall it and reboot when I open Cydia again, the package is still installed for whatever reason.

**Comment by ZakME** [comment]
Try uninstalling the tweak in safe mode. I woke up to my phone randomly rebooting today (in an unjailbroken state) about every 30 seconds and figured it may be this tweak since it was the last I installed so after many attempts trying to get into a jailbroken state, I entered safe mode using killall -11 SpringBoard in newterm and uninstalled the tweak. It hasn't rebooted yet and the tweak is not on the installed list in cydia.

**Comment by nicho1asdev** [comment]
It does work I just realized (I’m sorry for that) but after some time all apps started crashing so I had to restore rootfs.
